global:
  days_to_report: 7
  smtp:
    server: "my.smtp.server"
    port: "587"
    tls: True
    user: "smtpauth@mydomain.com"
    password: "password"
    from_addr: "reports@acme.com"
    cc_addrs:
      - ""
      - ""
    template: "team-summary.html"

plugins:
  - name: "ec2"
    friendly_name: "EC2"
    # data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ec2costsbyemail"
    aws_ce:
      group_by_tag: "acme:email"
      filter:
        # This filter gets all EC2 costs from all linked accounts other than the one specified
        And:
          - Not:
              Dimensions:
                Key: "LINKED_ACCOUNT"
                Values:
                  - "123456789012"
          - Dimensions:
              Key: SERVICE
              Values:
                - "Amazon Elastic Compute Cloud - Compute"
                - "EC2 - Other"
                - "Amazon Elastic Load Balancing"
                - "AWS Key Management Service"
                - "AWS Lambda"


  - name: "ecs"
    friendly_name: "ECS"
    # data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ecscostsbyemail"
    aws_ce:
      group_by_tag: "aws:cloudformation:stack-name"
      filter:
        # This filter gets all ECS costs from all linked accounts other than the one specified
        Not:
          Dimensions:
            Key: "LINKED_ACCOUNT"
            Values:
              - "123456789012"

  - name: "s3"
    friendly_name: "S3 Storage"
    # data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=s3costsbyemail"
    aws_ce:
      group_by_tag: "acme:email"
      filter:
        # This filter gets all S3 costs from all linked accounts other than the one specified
        And:
          - Not:
              Dimensions:
                Key: "LINKED_ACCOUNT"
                Values:
                  - "123456789012"
          - Dimensions:
              Key: SERVICE
              Values:
                - "Amazon Simple Storage Service"

  - name: "eb"
    friendly_name: "Elastic Beanstalk"
    # data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ebcostsbyenv"
    aws_ce:
      group_by_tag: "elasticbeanstalk:environment-name"
      filter:
        # This filter gets all EB costs from all linked accounts other than the one specified
        Not:
          Dimensions:
            Key: "LINKED_ACCOUNT"
            Values:
              - "123456789012"


  - name : "dynamodb"
    friendly_name: "DynamoDB"
    # data_url: "https://api.cloudcheckr.com/api/inventory.json/get_resources_dynamodb_details?access_key=BLAH"
    #aws_dynamodb:
    #  accounts:
    #    - name: "Account 1"
    #      credentials:
    #        role_arn: "arn:aws:iam::234567890123:role/ATCR_Role"
    #        external_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    #      regions:
    #        - "us-east-1"
    #        - "us-west-2"
    #    - name: "Account 2"
    #      credentials:
    #        role_arn: "arn:aws:iam::345678901234:role/ATCR_Role"
    #        external_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    #      regions:
    #        - "us-west-1"
    #        - "eu-west-1"
    aws_ce:
      group_by_tag: "table-name"
      filter:
        And:
          - Not:
              Dimensions:
                Key: "LINKED_ACCOUNT"
                Values:
                  - "123456789012"
          - Dimensions:
              Key: SERVICE
              Values:
                - "Amazon DynamoDB"


teams:
  - name: "one"
    email: "team-one@acme.com"
    budget: 2000
    other_costs_weight: 50
    members:
      - "user1@acme.com"
      - "user2@acme.com"
      - "user3@acme.com"
    ec2:
      include_tag: "acme:email"
    s3:
      include_tag: "acme:email"
    eb:
      include_tag: "elasticbeanstalk:environment-name"
      envs:
        - "EB-ENV-1"
        - "EB-ENV-2"
    ecs:
      include_tag: "aws:cloudformation:stack-name"
      envs:
        - "ECS-Cluster_one"
        - "ECS-Cluster-two"
    dynamodb:
      include_tag: "table-name"
      tables:
        - "teamone*"
        - "AutomatedTestReports"
        - "*somedata*"

  - name: "two"
    email: "team-two@acme.com"
    budget: 2000
    other_costs_weight: 50
    members:
      - "user10@acme.com"
      - "user20@acme.com"
      - "user30@acme.com"
    ec2:
      include_tag: "acme:email"
    s3:
      include_tag: "acme:email"
    eb:
      include_tag: "elasticbeanstalk:environment-name"
      envs:
        - "*team-two*"
    ecs:
      include_tag: "aws:cloudformation:stack-name"
      envs:
        - ""
    dynamodb:
      tables:
        - "TEAM-TWO*"
