global:
  days_to_report: 7
  smtp:
    server: "my.smtp.server"
    port: "587"
    tls: True
    user: "smtpauth@mydomain.com"
    password: "password"
    from_addr: "reports@acme.com"
    cc_addr: ""
    template: "team-summary.html"

plugins:
  - name: "ec2"
    friendly_name: "EC2"
    data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ec2costsbyemail"

  - name: "ecs"
    friendly_name: "ECS"
    data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ecscostsbyemail"

  - name: "s3"
    friendly_name: "S3 Storage"
    data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=s3costsbyemail"

  - name: "eb"
    friendly_name: "Elastic Beanstalk"
    data_url: "https://api.cloudcheckr.com/api/billing.json/get_detailed_billing_with_grouping?access_key=BLAH&saved_filter_name=ebcostsbyenv"

  - name : "dynamodb"
    friendly_name: "DynamoDB"
    data_url: "https://api.cloudcheckr.com/api/inventory.json/get_resources_dynamodb_details?access_key=BLAH"

teams:
  - name: "one"
    email: "team-one@acme.com"
    budget: 2000
    other_costs_weight: 50
    members:
      - "user1@acme.com"
      - "user2@acme.com"
      - "user3@acme.com"
    ec2:
      include_tag: "acme:email"
    s3:
      include_tag: "acme:email"
    eb:
      include_tag: "elasticbeanstalk:environment-name"
      envs:
        - "EB-ENV-1"
        - "EB-ENV-2"
    ecs:
      include_tag: "aws:cloudformation:stack-name"
      envs:
        - "ECS-Cluster_one"
        - "ECS-Cluster-two"
    dynamodb:
      tables:
        - "teamone*"
        - "AutomatedTestReports"
        - "*somedata*"

  - name: "two"
    email: "team-two@acme.com"
    budget: 2000
    other_costs_weight: 50
    members:
      - "user10@acme.com"
      - "user20@acme.com"
      - "user30@acme.com"
    ec2:
      include_tag: "acme:email"
    s3:
      include_tag: "acme:email"
    eb:
      include_tag: "elasticbeanstalk:environment-name"
      envs:
        - "*team-two*"
    ecs:
      include_tag: "aws:cloudformation:stack-name"
      envs:
        - ""
    dynamodb:
      tables:
        - "TEAM-TWO*"
